[build]
  functions = "netlify/functions"
  environment = { SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,SMTP_HOST,SMTP_PORT,SMTP_USER,SMTP_PASS" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200