[build]
  functions = "netlify/functions"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200